"""Auto-generated catalog data (from dataset/products.xlsx + curated catalog).
Do not edit by hand — regenerate with dataset/generate_catalog_data.py.
"""

CATALOG = [
    {"category": 'Vegetables', "slug": 'vegetables', "display_order": 1},
    {"category": 'Fruits', "slug": 'fruits', "display_order": 2},
    {"category": 'Dairy', "slug": 'dairy', "display_order": 3},
    {"category": 'Grains', "slug": 'grains', "display_order": 4},
    {"category": 'Spices', "slug": 'spices', "display_order": 5},
    {"category": 'Snacks', "slug": 'snacks', "display_order": 6},
    {"category": 'Leaves', "slug": 'leaves', "display_order": 9},
    {"category": 'Pickle Items', "slug": 'pickle-items', "display_order": 10},
    {"category": 'Karam Powders', "slug": 'karam-powders', "display_order": 8},
    {"category": 'Grocery', "slug": 'grocery', "display_order": 7},
]

PRODUCTS = [
    ('Amla Pickle', 'Pickle Items', '🫙', 6, 'jar', 'veg', 'Traditional Andhra-style amla (Indian gooseberry) pickle.'),
    ('Anand Finger Millets', 'Grocery', '🌾', 6.99, 'pack', 'veg', 'Finger millet flour, a nutritious traditional grain.'),
    ('Anand Little Millet', 'Grocery', '🌾', 6.99, 'pack', 'veg', 'Little millet, a traditional nutritious grain.'),
    ('Andhra Avakaya Pickle (Mango)', 'Pickle Items', '🫙', 6, 'jar', 'veg', 'Traditional spicy Andhra mango pickle made with raw mango, red chilli, and mustard.'),
    ('Andhra Tomato Pickle', 'Pickle Items', '🫙', 5.85, 'jar', 'veg', 'Spicy Andhra-style tomato pickle.'),
    ('Apples (Gala)', 'Fruits', '🍎', 2.99, 'lb', 'veg', 'Crunchy, sweet Gala apples.'),
    ('Bambino Roasted Vermicelli', 'Grocery', '🍝', 2.49, 'pack', 'veg', 'Roasted vermicelli, ready for upma and kheer preparations.'),
    ('Bananas', 'Fruits', '🍌', 0.59, 'lb', 'veg', 'Sweet ripe bananas — a household staple.'),
    ('Basmati Rice', 'Grains', '🍚', 8.99, '5lb', 'veg', 'Aged long-grain basmati rice, fluffy every time.'),
    ('Betel Leaves', 'Leaves', '🌿', 0.85, 'bunch', 'veg', 'Fresh betel leaves, traditionally used in paan and religious ceremonies.'),
    ('Bhel Patra', 'Leaves', '🌿', 1, 'bunch', 'veg', 'Bilva (bel) leaves, traditionally offered during Shiva puja.'),
    ('Biscuits (Parle-G)', 'Snacks', '🍪', 1.99, 'pack', 'veg', 'Classic Parle-G biscuits — a family favorite.'),
    ('Bittergourd Pickle', 'Pickle Items', '🫙', 5.85, 'jar', 'veg', 'Andhra-style bitter gourd pickle.'),
    ('Brinjal Pickle', 'Pickle Items', '🫙', 5.85, 'jar', 'veg', 'Traditional brinjal (eggplant) pickle.'),
    ('Chicken (Leg Quarters)', 'Snacks', '🍗', 2.99, 'lb', 'nonveg', 'Fresh chicken leg quarters, cleaned and ready.'),
    ('Cilantro', 'Vegetables', '🌿', 0.99, 'bunch', 'veg', 'Fresh coriander leaves to finish any dish.'),
    ('Cucumber', 'Vegetables', '🥒', 1.19, 'lb', 'veg', 'Cool, crisp cucumbers for salads and raita.'),
    ('Cumin Seeds (Jeera)', 'Spices', '⚫', 3.49, '200g', 'veg', 'Aromatic cumin seeds for tadka and masalas.'),
    ('Curd / Yogurt', 'Dairy', '🥣', 2.29, 'qt', 'veg', 'Thick, fresh-set yogurt for everyday meals.'),
    ('Deep Sooji Rava', 'Grocery', '🌾', 4.99, 'pack', 'veg', 'Fine semolina (sooji/rava), used for upma, halwa and more.'),
    ('Drumstick Pickle', 'Pickle Items', '🫙', 5.78, 'jar', 'veg', 'Traditional drumstick (moringa) pickle.'),
    ('Eggs (Dozen)', 'Snacks', '🥚', 3.49, '12', 'nonveg', 'Farm-fresh eggs, one dozen.'),
    ('Fresh Tomatoes', 'Vegetables', '🍅', 2.49, 'lb', 'veg', 'Ripe, farm-fresh tomatoes — perfect for curries, salads and chutneys.'),
    ('Gongura Pickle', 'Pickle Items', '🫙', 6, 'jar', 'veg', 'Traditional Andhra gongura (sorrel leaves) pickle, tangy and spicy.'),
    ('Green Chili', 'Vegetables', '🫑', 1.49, 'lb', 'veg', 'Hot green chillies, great for curries and pickles.'),
    ('Green Chilli Pickle', 'Pickle Items', '🫙', 5.85, 'jar', 'veg', 'Spicy green chilli pickle.'),
    ('Idli Karam Podi', 'Karam Powders', '🧂', 6.28, 'pack', 'veg', 'Spiced lentil powder traditionally eaten with idli and dosa.'),
    ('Kandi Karam Podi', 'Karam Powders', '🧂', 6.28, 'pack', 'veg', 'Toor dal-based spice powder, a staple Andhra side for rice.'),
    ('Karivepaku Karam Podi', 'Karam Powders', '🧂', 6.43, 'pack', 'veg', 'Curry leaf spice powder, aromatic and eaten with rice or idli.'),
    ('Karivepaku Pickle', 'Pickle Items', '🫙', 5.92, 'jar', 'veg', 'Curry leaves pickle, aromatic and spicy, an Andhra specialty.'),
    ('Kobbari Karam Podi', 'Karam Powders', '🧂', 6.5, 'pack', 'veg', 'Coconut-based spice powder, a South Indian staple.'),
    ('Kothimeera Karam Podi', 'Karam Powders', '🧂', 6.43, 'pack', 'veg', 'Coriander leaf spice powder, tangy and aromatic.'),
    ('Kothimeera Pickle', 'Pickle Items', '🫙', 5.92, 'jar', 'veg', 'Coriander leaves pickle, a tangy Andhra specialty.'),
    ('Mango Leaves', 'Leaves', '🌿', 3.5, 'bunch', 'veg', 'Fresh mango leaves, used for festive door decorations (toranam) and religious occasions.'),
    ('Mangoes (Alphonso)', 'Fruits', '🥭', 3.49, 'each', 'veg', 'Premium Alphonso mangoes in season.'),
    ('Mehandi Leaves (Fresh)', 'Leaves', '🌿', 18, 'bunch', 'veg', 'Freshly harvested Mehandi (Gorintaku) leaves, carefully packed for freshness. Ideal for preparing natural henna paste and for use during traditional festivals, pujas, weddings, and other auspicious occasions.'),
    ('Murukulu', 'Snacks', '🥨', 5.99, 'pack', 'veg', 'Crispy Andhra-style murukulu snack.'),
    ('Neem Leaves', 'Leaves', '🌿', 3, 'bunch', 'veg', 'Fresh neem leaves, used in traditional remedies and religious rituals.'),
    ('Nuvvula Karam Podi', 'Karam Powders', '🧂', 6.43, 'pack', 'veg', 'Sesame seed spice powder, nutty and rich.'),
    ('Onions', 'Vegetables', '🧅', 1.29, 'lb', 'veg', 'Crisp red onions, ideal for tadka and daily cooking.'),
    ('Palli Karam Podi', 'Karam Powders', '🧂', 6.5, 'pack', 'veg', 'Peanut-based spice powder, a popular rice accompaniment.'),
    ('Paneer', 'Dairy', '🧀', 4.99, 'lb', 'veg', 'Soft Indian cottage cheese, ready to cook.'),
    ('Potatoes', 'Vegetables', '🥔', 1.99, 'lb', 'veg', 'Sturdy all-purpose potatoes for curries, fries and roasts.'),
    ('Premium Small Peanuts', 'Grocery', '🥜', 8.99, 'pack', 'veg', 'Small variety raw peanuts.'),
    ('Pudina Karam Podi', 'Karam Powders', '🧂', 6.43, 'pack', 'veg', 'Mint leaf spice powder, refreshing and spicy.'),
    ('Red Chili Powder', 'Spices', '🌶️', 2.99, '200g', 'veg', 'Fiery red chilli powder for authentic heat.'),
    ('Toor Dal', 'Grains', '🥜', 4.49, 'lb', 'veg', 'Split pigeon peas — the base for a classic dal.'),
    ('Turmeric Powder', 'Spices', '🟡', 2.79, '200g', 'veg', 'Pure ground turmeric for cooking and wellness.'),
    ('Wheat Atta', 'Grains', '🌾', 6.99, '5lb', 'veg', 'Whole-wheat flour for soft rotis and parathas.'),
    ('Whole Milk', 'Dairy', '🥛', 3.99, 'gal', 'veg', 'Fresh whole milk, delivered chilled.'),
]

SEARCH_TERMS = [
    ('Mehandi Leaves (Fresh)', 'mehandi leaves', 'official', 'None'),
    ('Mehandi Leaves (Fresh)', 'mehandi', 'alias', 'Hindi'),
    ('Mehandi Leaves (Fresh)', 'mehendi', 'alias', 'Hindi'),
    ('Mehandi Leaves (Fresh)', 'henna', 'alias', 'None'),
    ('Mehandi Leaves (Fresh)', 'heena', 'alias', 'None'),
    ('Mehandi Leaves (Fresh)', 'gorintaku', 'regional', 'Telugu'),
    ('Mehandi Leaves (Fresh)', 'goranti', 'regional', 'Telugu'),
    ('Mehandi Leaves (Fresh)', 'marudhani', 'regional', 'Tamil'),
    ('Mehandi Leaves (Fresh)', 'marutham', 'regional', 'Tamil'),
    ('Mehandi Leaves (Fresh)', 'lawsonia inermis', 'alias', 'None'),
    ('Mehandi Leaves (Fresh)', 'gorintuku', 'typo', 'None'),
    ('Mehandi Leaves (Fresh)', 'gorantaku', 'typo', 'None'),
    ('Mehandi Leaves (Fresh)', 'gointaku', 'typo', 'None'),
    ('Mehandi Leaves (Fresh)', 'grointaku', 'typo', 'None'),
    ('Mehandi Leaves (Fresh)', '#henna', 'hashtag', 'None'),
    ('Mehandi Leaves (Fresh)', '#mehendi', 'hashtag', 'None'),
    ('Mehandi Leaves (Fresh)', '#gorintaku', 'hashtag', 'None'),
    ('Mehandi Leaves (Fresh)', '#naturaldye', 'hashtag', 'None'),
    ('Turmeric Powder', 'turmeric powder', 'official', 'None'),
    ('Turmeric Powder', 'turmeric', 'alias', 'None'),
    ('Turmeric Powder', 'haldi', 'regional', 'Hindi'),
    ('Turmeric Powder', 'pasupu', 'regional', 'Telugu'),
    ('Turmeric Powder', 'manjal', 'regional', 'Tamil'),
    ('Turmeric Powder', 'arishina', 'regional', 'Kannada'),
    ('Turmeric Powder', 'curcuma', 'alias', 'None'),
    ('Turmeric Powder', 'turmaric', 'typo', 'None'),
    ('Turmeric Powder', 'tumeric', 'typo', 'None'),
    ('Turmeric Powder', 'haldii', 'typo', 'None'),
    ('Turmeric Powder', '#turmeric', 'hashtag', 'None'),
    ('Turmeric Powder', '#haldi', 'hashtag', 'None'),
    ('Turmeric Powder', '#naturalspice', 'hashtag', 'None'),
    ('Betel Leaves', 'paan leaves', 'alias', 'None'),
    ('Betel Leaves', 'tamboolam', 'regional', 'Telugu'),
    ('Betel Leaves', 'vetrilai', 'regional', 'Tamil'),
    ('Betel Leaves', 'paan aaku', 'regional', 'Telugu'),
    ('Betel Leaves', 'beetle leaves', 'typo', 'None'),
    ('Betel Leaves', '#betelleaves', 'hashtag', 'None'),
    ('Mango Leaves', 'mamidi aaku', 'regional', 'Telugu'),
    ('Mango Leaves', 'mangai ilai', 'regional', 'Tamil'),
    ('Mango Leaves', 'toranam leaves', 'alias', 'None'),
    ('Mango Leaves', 'mango tree leaves', 'typo', 'None'),
    ('Mango Leaves', '#mangoleaves', 'hashtag', 'None'),
    ('Neem Leaves', 'vepaku', 'regional', 'Telugu'),
    ('Neem Leaves', 'veppilai', 'regional', 'Tamil'),
    ('Neem Leaves', 'margosa leaves', 'alias', 'None'),
    ('Neem Leaves', 'neem patta', 'regional', 'Hindi'),
    ('Neem Leaves', 'niim leaves', 'typo', 'None'),
    ('Neem Leaves', '#neemleaves', 'hashtag', 'None'),
    ('Bhel Patra', 'bilva patra', 'alias', 'None'),
    ('Bhel Patra', 'bel patta', 'alias', 'Hindi'),
    ('Bhel Patra', 'maredu aaku', 'regional', 'Telugu'),
    ('Bhel Patra', 'bael leaves', 'typo', 'None'),
    ('Bhel Patra', '#bhelpatra', 'hashtag', 'None'),
    ('Amla Pickle', 'usirikaya pachadi', 'regional', 'Telugu'),
    ('Amla Pickle', 'nellikai pickle', 'regional', 'Tamil'),
    ('Amla Pickle', 'gooseberry pickle', 'alias', 'None'),
    ('Amla Pickle', 'amla achar', 'alias', 'Hindi'),
    ('Amla Pickle', 'amala pickle', 'typo', 'None'),
    ('Amla Pickle', '#amlapickle', 'hashtag', 'None'),
    ('Andhra Avakaya Pickle (Mango)', 'avakaya', 'regional', 'Telugu'),
    ('Andhra Avakaya Pickle (Mango)', 'aavakaya', 'regional', 'Telugu'),
    ('Andhra Avakaya Pickle (Mango)', 'mango pickle', 'alias', 'None'),
    ('Andhra Avakaya Pickle (Mango)', 'avakai', 'typo', 'None'),
    ('Andhra Avakaya Pickle (Mango)', '#avakaya', 'hashtag', 'None'),
    ('Andhra Tomato Pickle', 'tomato pachadi', 'regional', 'Telugu'),
    ('Andhra Tomato Pickle', 'thakkali pickle', 'regional', 'Tamil'),
    ('Andhra Tomato Pickle', 'tamata achar', 'alias', 'Hindi'),
    ('Andhra Tomato Pickle', 'tamato pickle', 'typo', 'None'),
    ('Andhra Tomato Pickle', '#tomatopickle', 'hashtag', 'None'),
    ('Bittergourd Pickle', 'kakarakaya pachadi', 'regional', 'Telugu'),
    ('Bittergourd Pickle', 'pavakkai pickle', 'regional', 'Tamil'),
    ('Bittergourd Pickle', 'karela pickle', 'alias', 'Hindi'),
    ('Bittergourd Pickle', 'bitter gourd pickle', 'alias', 'None'),
    ('Bittergourd Pickle', 'bittergourd achar', 'typo', 'None'),
    ('Bittergourd Pickle', '#bittergourdpickle', 'hashtag', 'None'),
    ('Brinjal Pickle', 'vankaya pachadi', 'regional', 'Telugu'),
    ('Brinjal Pickle', 'kathirikai pickle', 'regional', 'Tamil'),
    ('Brinjal Pickle', 'baingan achar', 'alias', 'Hindi'),
    ('Brinjal Pickle', 'eggplant pickle', 'alias', 'None'),
    ('Brinjal Pickle', 'brinjal achar', 'typo', 'None'),
    ('Brinjal Pickle', '#brinjalpickle', 'hashtag', 'None'),
    ('Gongura Pickle', 'gongura pachadi', 'regional', 'Telugu'),
    ('Gongura Pickle', 'pulicha keerai pickle', 'regional', 'Tamil'),
    ('Gongura Pickle', 'sorrel leaves pickle', 'alias', 'None'),
    ('Gongura Pickle', 'gonkura pickle', 'typo', 'None'),
    ('Gongura Pickle', '#gongura', 'hashtag', 'None'),
    ('Green Chilli Pickle', 'pachi mirapakaya pachadi', 'regional', 'Telugu'),
    ('Green Chilli Pickle', 'milagai pickle', 'regional', 'Tamil'),
    ('Green Chilli Pickle', 'hari mirch achar', 'alias', 'Hindi'),
    ('Green Chilli Pickle', 'green chili pickle', 'typo', 'None'),
    ('Green Chilli Pickle', '#greenchillipickle', 'hashtag', 'None'),
    ('Karivepaku Pickle', 'curry leaves pickle', 'alias', 'None'),
    ('Karivepaku Pickle', 'karivepaku pachadi', 'regional', 'Telugu'),
    ('Karivepaku Pickle', 'kariveppilai pickle', 'regional', 'Tamil'),
    ('Karivepaku Pickle', 'curry patta achar', 'alias', 'Hindi'),
    ('Karivepaku Pickle', 'karivepaku pickel', 'typo', 'None'),
    ('Karivepaku Pickle', '#curryleavespickle', 'hashtag', 'None'),
    ('Kothimeera Pickle', 'coriander pickle', 'alias', 'None'),
    ('Kothimeera Pickle', 'kothimeera pachadi', 'regional', 'Telugu'),
    ('Kothimeera Pickle', 'kothamalli pickle', 'regional', 'Tamil'),
    ('Kothimeera Pickle', 'dhaniya achar', 'alias', 'Hindi'),
    ('Kothimeera Pickle', 'kothimira pickle', 'typo', 'None'),
    ('Kothimeera Pickle', '#corianderpickle', 'hashtag', 'None'),
    ('Drumstick Pickle', 'munagakaya pachadi', 'regional', 'Telugu'),
    ('Drumstick Pickle', 'murungakkai pickle', 'regional', 'Tamil'),
    ('Drumstick Pickle', 'moringa pickle', 'alias', 'None'),
    ('Drumstick Pickle', 'sahjan achar', 'alias', 'Hindi'),
    ('Drumstick Pickle', 'drum stick pickle', 'typo', 'None'),
    ('Drumstick Pickle', '#drumstickpickle', 'hashtag', 'None'),
    ('Anand Finger Millets', 'ragi', 'regional', 'Telugu/Kannada'),
    ('Anand Finger Millets', 'ragulu', 'regional', 'Telugu'),
    ('Anand Finger Millets', 'nachni', 'regional', 'Hindi'),
    ('Anand Finger Millets', 'finger millet flour', 'alias', 'None'),
    ('Anand Finger Millets', 'ragee', 'typo', 'None'),
    ('Anand Finger Millets', '#fingermillet', 'hashtag', 'None'),
    ('Anand Little Millet', 'samalu', 'regional', 'Telugu'),
    ('Anand Little Millet', 'samai', 'regional', 'Tamil'),
    ('Anand Little Millet', 'kutki', 'regional', 'Hindi'),
    ('Anand Little Millet', 'little millet flour', 'alias', 'None'),
    ('Anand Little Millet', 'littel millet', 'typo', 'None'),
    ('Anand Little Millet', '#littlemillet', 'hashtag', 'None'),
    ('Premium Small Peanuts', 'verusenaga pappu', 'regional', 'Telugu'),
    ('Premium Small Peanuts', 'verkadalai', 'regional', 'Tamil'),
    ('Premium Small Peanuts', 'mungfali', 'regional', 'Hindi'),
    ('Premium Small Peanuts', 'groundnuts', 'alias', 'None'),
    ('Premium Small Peanuts', 'peanutts', 'typo', 'None'),
    ('Premium Small Peanuts', '#peanuts', 'hashtag', 'None'),
    ('Deep Sooji Rava', 'sooji', 'alias', 'Hindi'),
    ('Deep Sooji Rava', 'rava', 'regional', 'Telugu/Tamil'),
    ('Deep Sooji Rava', 'semolina', 'alias', 'None'),
    ('Deep Sooji Rava', 'bombay rava', 'alias', 'None'),
    ('Deep Sooji Rava', 'suji', 'typo', 'None'),
    ('Deep Sooji Rava', '#semolina', 'hashtag', 'None'),
    ('Bambino Roasted Vermicelli', 'semiya', 'regional', 'Tamil/Telugu'),
    ('Bambino Roasted Vermicelli', 'sevai', 'regional', 'Hindi'),
    ('Bambino Roasted Vermicelli', 'vermicilli', 'typo', 'None'),
    ('Bambino Roasted Vermicelli', 'roasted semiya', 'alias', 'None'),
    ('Bambino Roasted Vermicelli', '#vermicelli', 'hashtag', 'None'),
    ('Idli Karam Podi', 'idli podi', 'alias', 'None'),
    ('Idli Karam Podi', 'idli milagai podi', 'regional', 'Tamil'),
    ('Idli Karam Podi', 'idly karam', 'typo', 'None'),
    ('Idli Karam Podi', '#idlipodi', 'hashtag', 'None'),
    ('Kandi Karam Podi', 'kandi podi', 'alias', 'None'),
    ('Kandi Karam Podi', 'toor dal powder', 'alias', 'None'),
    ('Kandi Karam Podi', 'kandhi karam', 'typo', 'None'),
    ('Kandi Karam Podi', '#kandipodi', 'hashtag', 'None'),
    ('Karivepaku Karam Podi', 'curry leaf powder', 'alias', 'None'),
    ('Karivepaku Karam Podi', 'karivepaku podi', 'alias', 'Telugu'),
    ('Karivepaku Karam Podi', 'curry leaves karam', 'typo', 'None'),
    ('Karivepaku Karam Podi', '#curryleafpowder', 'hashtag', 'None'),
    ('Kobbari Karam Podi', 'coconut podi', 'alias', 'None'),
    ('Kobbari Karam Podi', 'kobbari podi', 'alias', 'Telugu'),
    ('Kobbari Karam Podi', 'kobbari karam', 'typo', 'None'),
    ('Kobbari Karam Podi', '#coconutpodi', 'hashtag', 'None'),
    ('Kothimeera Karam Podi', 'coriander podi', 'alias', 'None'),
    ('Kothimeera Karam Podi', 'kothimeera podi', 'alias', 'Telugu'),
    ('Kothimeera Karam Podi', 'kothimira karam', 'typo', 'None'),
    ('Kothimeera Karam Podi', '#corianderpodi', 'hashtag', 'None'),
    ('Nuvvula Karam Podi', 'sesame podi', 'alias', 'None'),
    ('Nuvvula Karam Podi', 'nuvvula podi', 'alias', 'Telugu'),
    ('Nuvvula Karam Podi', 'til powder', 'regional', 'Hindi'),
    ('Nuvvula Karam Podi', 'nuvulla karam', 'typo', 'None'),
    ('Nuvvula Karam Podi', '#sesamepodi', 'hashtag', 'None'),
    ('Palli Karam Podi', 'peanut podi', 'alias', 'None'),
    ('Palli Karam Podi', 'palli podi', 'alias', 'Telugu'),
    ('Palli Karam Podi', 'groundnut powder', 'alias', 'None'),
    ('Palli Karam Podi', 'pally karam', 'typo', 'None'),
    ('Palli Karam Podi', '#peanutpodi', 'hashtag', 'None'),
    ('Pudina Karam Podi', 'mint podi', 'alias', 'None'),
    ('Pudina Karam Podi', 'pudina podi', 'alias', 'Telugu/Hindi'),
    ('Pudina Karam Podi', 'pudhina karam', 'typo', 'None'),
    ('Pudina Karam Podi', '#mintpodi', 'hashtag', 'None'),
    ('Fresh Tomatoes', 'tomato', 'alias', 'English'),
    ('Fresh Tomatoes', 'tamatar', 'regional', 'Hindi'),
    ('Fresh Tomatoes', 'thakkali', 'regional', 'Tamil'),
    ('Fresh Tomatoes', 'tamata', 'regional', 'Telugu'),
    ('Onions', 'onion', 'alias', 'English'),
    ('Onions', 'pyaz', 'regional', 'Hindi'),
    ('Onions', 'ulli', 'regional', 'Tamil'),
    ('Onions', 'ullipaya', 'regional', 'Telugu'),
    ('Potatoes', 'potato', 'alias', 'English'),
    ('Potatoes', 'aalu', 'regional', 'Hindi'),
    ('Potatoes', 'urulaikizhangu', 'regional', 'Tamil'),
    ('Potatoes', 'bangaladumpa', 'regional', 'Telugu'),
    ('Cilantro', 'coriander', 'alias', 'English'),
    ('Cilantro', 'dhania', 'regional', 'Hindi'),
    ('Cilantro', 'kothamalli', 'regional', 'Tamil'),
    ('Cilantro', 'kothimeera', 'regional', 'Telugu'),
    ('Green Chili', 'green chilli', 'alias', 'English'),
    ('Green Chili', 'hari mirch', 'regional', 'Hindi'),
    ('Green Chili', 'pachai milagai', 'regional', 'Tamil'),
    ('Green Chili', 'pacchi mirchi', 'regional', 'Telugu'),
    ('Cucumber', 'cucumber', 'alias', 'English'),
    ('Cucumber', 'khira', 'regional', 'Hindi'),
    ('Cucumber', 'vellari', 'regional', 'Tamil'),
    ('Cucumber', 'dosakaya', 'regional', 'Telugu'),
    ('Bananas', 'banana', 'alias', 'English'),
    ('Bananas', 'kela', 'regional', 'Hindi'),
    ('Bananas', 'valaipazham', 'regional', 'Tamil'),
    ('Bananas', 'arati', 'regional', 'Telugu'),
    ('Apples (Gala)', 'apple', 'alias', 'English'),
    ('Apples (Gala)', 'seb', 'regional', 'Hindi'),
    ('Apples (Gala)', 'apple pazham', 'regional', 'Tamil'),
    ('Apples (Gala)', 'appil', 'regional', 'Telugu'),
    ('Mangoes (Alphonso)', 'mango', 'alias', 'English'),
    ('Mangoes (Alphonso)', 'aam', 'regional', 'Hindi'),
    ('Mangoes (Alphonso)', 'mango pazham', 'regional', 'Tamil'),
    ('Mangoes (Alphonso)', 'mamidi', 'regional', 'Telugu'),
    ('Whole Milk', 'milk', 'alias', 'English'),
    ('Whole Milk', 'doodh', 'regional', 'Hindi'),
    ('Whole Milk', 'paal', 'regional', 'Tamil'),
    ('Whole Milk', 'paalu', 'regional', 'Telugu'),
    ('Curd / Yogurt', 'curd', 'alias', 'English'),
    ('Curd / Yogurt', 'yogurt', 'alias', 'English'),
    ('Curd / Yogurt', 'dahi', 'regional', 'Hindi'),
    ('Curd / Yogurt', 'thayir', 'regional', 'Tamil'),
    ('Curd / Yogurt', 'perugu', 'regional', 'Telugu'),
    ('Paneer', 'paneer', 'alias', 'English'),
    ('Paneer', 'chena', 'regional', 'Hindi'),
    ('Basmati Rice', 'basmati', 'alias', 'English'),
    ('Basmati Rice', 'biryani rice', 'alias', 'English'),
    ('Basmati Rice', 'basmati annam', 'regional', 'Telugu'),
    ('Toor Dal', 'toor dal', 'alias', 'English'),
    ('Toor Dal', 'arhar dal', 'regional', 'Hindi'),
    ('Toor Dal', 'thuvaram paruppu', 'regional', 'Tamil'),
    ('Toor Dal', 'kandi pappu', 'regional', 'Telugu'),
    ('Wheat Atta', 'atta', 'alias', 'English'),
    ('Wheat Atta', 'wheat flour', 'alias', 'English'),
    ('Wheat Atta', 'gehu ka atta', 'regional', 'Hindi'),
    ('Wheat Atta', 'godhuma pindi', 'regional', 'Telugu'),
    ('Red Chili Powder', 'red chilli powder', 'alias', 'English'),
    ('Red Chili Powder', 'lal mirch', 'regional', 'Hindi'),
    ('Red Chili Powder', 'kandam', 'regional', 'Telugu'),
    ('Cumin Seeds (Jeera)', 'jeera', 'alias', 'English'),
    ('Cumin Seeds (Jeera)', 'cumin', 'alias', 'English'),
    ('Cumin Seeds (Jeera)', 'zeera', 'regional', 'Hindi'),
    ('Cumin Seeds (Jeera)', 'seeragam', 'regional', 'Tamil'),
    ('Cumin Seeds (Jeera)', 'jilakara', 'regional', 'Telugu'),
    ('Chicken (Leg Quarters)', 'chicken', 'alias', 'English'),
    ('Chicken (Leg Quarters)', 'murgi', 'regional', 'Hindi'),
    ('Chicken (Leg Quarters)', 'kozi', 'regional', 'Tamil'),
    ('Chicken (Leg Quarters)', 'kodi', 'regional', 'Telugu'),
    ('Eggs (Dozen)', 'eggs', 'alias', 'English'),
    ('Eggs (Dozen)', 'ande', 'regional', 'Hindi'),
    ('Eggs (Dozen)', 'mutta', 'regional', 'Tamil'),
    ('Eggs (Dozen)', 'guddu', 'regional', 'Telugu'),
    ('Murukulu', 'murukku', 'alias', 'English'),
    ('Murukulu', 'chakli', 'alias', 'English'),
    ('Murukulu', 'murukulu', 'alias', 'Telugu'),
    ('Biscuits (Parle-G)', 'parle-g', 'alias', 'English'),
    ('Biscuits (Parle-G)', 'biscuit', 'alias', 'English'),
]
