-- AUTO-GENERATED by dataset/import_dataset.py — do not edit by hand.
-- Source: dataset/products.xlsx
-- Safe to re-run: uses NOT EXISTS / ON CONFLICT guards.

INSERT INTO categories (category_name) VALUES ('Leaves') ON CONFLICT (category_name) DO NOTHING;

INSERT INTO products (category_id, product_name, scientific_name, description, price, stock_quantity, image_url)
SELECT category_id, 'Mehandi Leaves (Fresh)', 'Lawsonia inermis', 'Freshly harvested Mehandi (Gorintaku) leaves, carefully packed for freshness. Ideal for preparing natural henna paste and for use during traditional festivals, pujas, weddings, and other auspicious occasions.', 18, 93, NULL
FROM categories WHERE category_name = 'Leaves'
AND NOT EXISTS (SELECT 1 FROM products WHERE product_name = 'Mehandi Leaves (Fresh)');

INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'mehandi leaves', 'official', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'mehandi', 'alias', 'Hindi'
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'mehendi', 'alias', 'Hindi'
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'henna', 'alias', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'heena', 'alias', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'gorintaku', 'regional', 'Telugu'
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'goranti', 'regional', 'Telugu'
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'marudhani', 'regional', 'Tamil'
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'marutham', 'regional', 'Tamil'
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'lawsonia inermis', 'alias', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'gorintuku', 'typo', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'gorantaku', 'typo', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'gointaku', 'typo', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, 'grointaku', 'typo', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, '#henna', 'hashtag', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, '#mehendi', 'hashtag', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, '#gorintaku', 'hashtag', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;
INSERT INTO search_terms (product_id, search_term, term_type, language)
SELECT product_id, '#naturaldye', 'hashtag', NULL
FROM products WHERE product_name = 'Mehandi Leaves (Fresh)'
ON CONFLICT (product_id, search_term) DO NOTHING;

